apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: py2svc-gitops
  description: This is GitOps manifest for py2svc   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: py2svc
    backstage.io/kubernetes-id: py2svc 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: py2svc   
spec:
  type: gitops
  owner: user:default/webchang 
  lifecycle: experimental
  dependsOn:
    - component:py2svc
