apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: py2svc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: py2svc 
  name: py2svc
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: py2svc 
